# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projects\btp8\Polyglot\screens\interactioncopy.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_player_window(object):
    def setupUi(self, player_window):
        player_window.setObjectName("player_window")
        player_window.setEnabled(True)
        player_window.resize(1067, 661)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(player_window.sizePolicy().hasHeightForWidth())
        player_window.setSizePolicy(sizePolicy)
        player_window.setAutoFillBackground(False)
        player_window.setStyleSheet("background: rgb(43, 46, 59);\n"
"")
        self.layout = QtWidgets.QWidget(player_window)
        self.layout.setMinimumSize(QtCore.QSize(1067, 661))
        self.layout.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.layout.setStyleSheet("QWidget#landing{\n"
"background: rgb(43, 46, 59);\n"
"}")
        self.layout.setObjectName("layout")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layout)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setSizeIncrement(QtCore.QSize(10, 10))
        self.frame.setBaseSize(QtCore.QSize(200, 800))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.instructions_l = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.instructions_l.sizePolicy().hasHeightForWidth())
        self.instructions_l.setSizePolicy(sizePolicy)
        self.instructions_l.setMinimumSize(QtCore.QSize(0, 60))
        self.instructions_l.setStyleSheet("font: 12pt \"MS Reference Sans Serif\";\n"
"color: white;")
        self.instructions_l.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.instructions_l.setScaledContents(False)
        self.instructions_l.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.instructions_l.setWordWrap(True)
        self.instructions_l.setObjectName("instructions_l")
        self.verticalLayout.addWidget(self.instructions_l)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.analyse_b_2 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyse_b_2.sizePolicy().hasHeightForWidth())
        self.analyse_b_2.setSizePolicy(sizePolicy)
        self.analyse_b_2.setMinimumSize(QtCore.QSize(250, 50))
        self.analyse_b_2.setBaseSize(QtCore.QSize(100, 100))
        self.analyse_b_2.setStyleSheet(":enabled {\n"
"border-radius: 0px;\n"
"font-family: Courier New;\n"
"color: #ffffff;\n"
"font-size: 14pt;\n"
"background: transparent;\n"
"padding: 10pt 20pt 10pt 20pt;\n"
"border: 5px solid #ffffff;\n"
"text-decoration: none;\n"
"}\n"
":hover {\n"
"background: white;\n"
"color: rgb(43, 46, 59);\n"
"border: 0px;\n"
"}")
        self.analyse_b_2.setDefault(False)
        self.analyse_b_2.setFlat(False)
        self.analyse_b_2.setObjectName("analyse_b_2")
        self.horizontalLayout.addWidget(self.analyse_b_2)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("font: 12pt \"MS Reference Sans Serif\";\n"
"color: white;")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.analyse_b_5 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyse_b_5.sizePolicy().hasHeightForWidth())
        self.analyse_b_5.setSizePolicy(sizePolicy)
        self.analyse_b_5.setMinimumSize(QtCore.QSize(120, 50))
        self.analyse_b_5.setBaseSize(QtCore.QSize(100, 100))
        self.analyse_b_5.setStyleSheet(":enabled {\n"
"border-radius: 0px;\n"
"font-family: Courier New;\n"
"color: #ffffff;\n"
"font-size: 14pt;\n"
"background: transparent;\n"
"padding: 10pt 20pt 10pt 20pt;\n"
"border: 5px solid #ffffff;\n"
"text-decoration: none;\n"
"}\n"
":hover {\n"
"background: white;\n"
"color: rgb(43, 46, 59);\n"
"border: 0px;\n"
"}")
        self.analyse_b_5.setDefault(False)
        self.analyse_b_5.setFlat(False)
        self.analyse_b_5.setObjectName("analyse_b_5")
        self.horizontalLayout_5.addWidget(self.analyse_b_5)
        spacerItem2 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.analyse_b_6 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyse_b_6.sizePolicy().hasHeightForWidth())
        self.analyse_b_6.setSizePolicy(sizePolicy)
        self.analyse_b_6.setMinimumSize(QtCore.QSize(120, 50))
        self.analyse_b_6.setBaseSize(QtCore.QSize(100, 100))
        self.analyse_b_6.setStyleSheet(":enabled {\n"
"border-radius: 0px;\n"
"font-family: Courier New;\n"
"color: #ffffff;\n"
"font-size: 14pt;\n"
"background: transparent;\n"
"padding: 10pt 20pt 10pt 20pt;\n"
"border: 5px solid #ffffff;\n"
"text-decoration: none;\n"
"}\n"
":hover {\n"
"background: white;\n"
"color: rgb(43, 46, 59);\n"
"border: 0px;\n"
"}")
        self.analyse_b_6.setDefault(False)
        self.analyse_b_6.setFlat(False)
        self.analyse_b_6.setObjectName("analyse_b_6")
        self.horizontalLayout_5.addWidget(self.analyse_b_6)
        spacerItem3 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.analyse_b_7 = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyse_b_7.sizePolicy().hasHeightForWidth())
        self.analyse_b_7.setSizePolicy(sizePolicy)
        self.analyse_b_7.setMinimumSize(QtCore.QSize(120, 50))
        self.analyse_b_7.setBaseSize(QtCore.QSize(100, 100))
        self.analyse_b_7.setStyleSheet(":enabled {\n"
"border-radius: 0px;\n"
"font-family: Courier New;\n"
"color: #ffffff;\n"
"font-size: 14pt;\n"
"background: transparent;\n"
"padding: 10pt 20pt 10pt 20pt;\n"
"border: 5px solid #ffffff;\n"
"text-decoration: none;\n"
"}\n"
":hover {\n"
"background: white;\n"
"color: rgb(43, 46, 59);\n"
"border: 0px;\n"
"}")
        self.analyse_b_7.setDefault(False)
        self.analyse_b_7.setFlat(False)
        self.analyse_b_7.setObjectName("analyse_b_7")
        self.horizontalLayout_5.addWidget(self.analyse_b_7)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem4)
        self.english_l = QtWidgets.QLabel(self.frame)
        self.english_l.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.english_l.sizePolicy().hasHeightForWidth())
        self.english_l.setSizePolicy(sizePolicy)
        self.english_l.setStyleSheet("font: 12pt \"MS Reference Sans Serif\";\n"
"color: white;")
        self.english_l.setObjectName("english_l")
        self.verticalLayout.addWidget(self.english_l)
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        spacerItem5 = QtWidgets.QSpacerItem(591, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.back_b = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_b.sizePolicy().hasHeightForWidth())
        self.back_b.setSizePolicy(sizePolicy)
        self.back_b.setMinimumSize(QtCore.QSize(150, 50))
        self.back_b.setBaseSize(QtCore.QSize(100, 100))
        self.back_b.setStyleSheet(":enabled {\n"
"border-radius: 0px;\n"
"font-family: Courier New;\n"
"color: #ffffff;\n"
"font-size: 14pt;\n"
"background: transparent;\n"
"padding: 10pt 20pt 10pt 20pt;\n"
"border: 5px solid #ffffff;\n"
"text-decoration: none;\n"
"}\n"
":hover {\n"
"background: white;\n"
"color: rgb(43, 46, 59);\n"
"border: 0px;\n"
"}")
        self.back_b.setDefault(False)
        self.back_b.setFlat(False)
        self.back_b.setObjectName("back_b")
        self.horizontalLayout_3.addWidget(self.back_b)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.analyse_b = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.analyse_b.sizePolicy().hasHeightForWidth())
        self.analyse_b.setSizePolicy(sizePolicy)
        self.analyse_b.setMinimumSize(QtCore.QSize(250, 50))
        self.analyse_b.setBaseSize(QtCore.QSize(100, 100))
        self.analyse_b.setStyleSheet(":enabled {\n"
"border-radius: 0px;\n"
"font-family: Courier New;\n"
"color: #ffffff;\n"
"font-size: 14pt;\n"
"background: transparent;\n"
"padding: 10pt 20pt 10pt 20pt;\n"
"border: 5px solid #ffffff;\n"
"text-decoration: none;\n"
"}\n"
":hover {\n"
"background: white;\n"
"color: rgb(43, 46, 59);\n"
"border: 0px;\n"
"}")
        self.analyse_b.setDefault(False)
        self.analyse_b.setFlat(False)
        self.analyse_b.setObjectName("analyse_b")
        self.horizontalLayout_3.addWidget(self.analyse_b)
        spacerItem7 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.graphTitle_l = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphTitle_l.sizePolicy().hasHeightForWidth())
        self.graphTitle_l.setSizePolicy(sizePolicy)
        self.graphTitle_l.setMinimumSize(QtCore.QSize(0, 60))
        self.graphTitle_l.setStyleSheet("font: 12pt \"MS Reference Sans Serif\";\n"
"color: white;")
        self.graphTitle_l.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.graphTitle_l.setWordWrap(True)
        self.graphTitle_l.setObjectName("graphTitle_l")
        self.verticalLayout_5.addWidget(self.graphTitle_l)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem8)
        self.graphWidget = PlotWidget(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphWidget.sizePolicy().hasHeightForWidth())
        self.graphWidget.setSizePolicy(sizePolicy)
        self.graphWidget.setAutoFillBackground(True)
        self.graphWidget.setStyleSheet("background: rgb(FF, FF, FF);")
        self.graphWidget.setObjectName("graphWidget")
        self.verticalLayout_5.addWidget(self.graphWidget)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(2, 10)
        self.gridLayout.addLayout(self.verticalLayout_5, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        player_window.setCentralWidget(self.layout)

        self.retranslateUi(player_window)
        QtCore.QMetaObject.connectSlotsByName(player_window)

    def retranslateUi(self, player_window):
        _translate = QtCore.QCoreApplication.translate
        player_window.setWindowTitle(_translate("player_window", "MainWindow"))
        self.instructions_l.setText(_translate("player_window", "Choose a directory with English, Hindi and Nepali sub-directories and analyze with available models."))
        self.analyse_b_2.setText(_translate("player_window", "Upload"))
        self.label.setText(_translate("player_window", "TextLabel"))
        self.analyse_b_5.setText(_translate("player_window", "Analyse"))
        self.analyse_b_6.setText(_translate("player_window", "Analyse"))
        self.analyse_b_7.setText(_translate("player_window", "Analyse"))
        self.english_l.setText(_translate("player_window", "results:"))
        self.back_b.setText(_translate("player_window", "Back"))
        self.analyse_b.setText(_translate("player_window", "Analyse"))
        self.graphTitle_l.setText(_translate("player_window", "Visualisation of sentence embeddings of different languages in 2D vector space"))
from pyqtgraph import PlotWidget
