# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Projects\btp8\Polyglot\screens\intro.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(1034, 583)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(mainWindow.sizePolicy().hasHeightForWidth())
        mainWindow.setSizePolicy(sizePolicy)
        mainWindow.setAutoFillBackground(False)
        mainWindow.setStyleSheet("background: rgb(43, 46, 59);\n"
"")
        self.landing = QtWidgets.QWidget(mainWindow)
        self.landing.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.landing.setStyleSheet("QWidget#landing{\n"
"background: rgb(43, 46, 59);\n"
"}")
        self.landing.setObjectName("landing")
        self.gridLayout = QtWidgets.QGridLayout(self.landing)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.landing)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setSizeIncrement(QtCore.QSize(10, 10))
        self.frame.setBaseSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.subtitle_l = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subtitle_l.sizePolicy().hasHeightForWidth())
        self.subtitle_l.setSizePolicy(sizePolicy)
        self.subtitle_l.setStyleSheet("font: 20pt \"MS Reference Sans Serif\";\n"
"color: white;")
        self.subtitle_l.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitle_l.setObjectName("subtitle_l")
        self.gridLayout_2.addWidget(self.subtitle_l, 8, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 7, 0, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 12, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 2)
        self.title_l = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.title_l.sizePolicy().hasHeightForWidth())
        self.title_l.setSizePolicy(sizePolicy)
        self.title_l.setMinimumSize(QtCore.QSize(0, 0))
        self.title_l.setMaximumSize(QtCore.QSize(1400, 500))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.title_l.setFont(font)
        self.title_l.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
"color: rgb(158,233,248);")
        self.title_l.setText("")
        self.title_l.setAlignment(QtCore.Qt.AlignCenter)
        self.title_l.setObjectName("title_l")
        self.gridLayout_2.addWidget(self.title_l, 5, 0, 1, 2, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 9, 0, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.start_sentence_b = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_sentence_b.sizePolicy().hasHeightForWidth())
        self.start_sentence_b.setSizePolicy(sizePolicy)
        self.start_sentence_b.setMinimumSize(QtCore.QSize(250, 50))
        self.start_sentence_b.setBaseSize(QtCore.QSize(100, 100))
        self.start_sentence_b.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.start_sentence_b.setStyleSheet(":enabled {\n"
"border-radius: 0px;\n"
"font-family: Courier New;\n"
"color: #ffffff;\n"
"font-size: 14pt;\n"
"background: transparent;\n"
"padding: 10pt 20pt 10pt 20pt;\n"
"border: 5px solid #ffffff;\n"
"text-decoration: none;\n"
"}\n"
":hover {\n"
"background: white;\n"
"color: rgb(43, 46, 59);\n"
"border: 0px;\n"
"}")
        self.start_sentence_b.setCheckable(False)
        self.start_sentence_b.setChecked(False)
        self.start_sentence_b.setDefault(False)
        self.start_sentence_b.setFlat(False)
        self.start_sentence_b.setObjectName("start_sentence_b")
        self.horizontalLayout_5.addWidget(self.start_sentence_b)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.start_upload_b = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_upload_b.sizePolicy().hasHeightForWidth())
        self.start_upload_b.setSizePolicy(sizePolicy)
        self.start_upload_b.setMinimumSize(QtCore.QSize(250, 50))
        self.start_upload_b.setBaseSize(QtCore.QSize(100, 100))
        self.start_upload_b.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.start_upload_b.setStyleSheet(":enabled {\n"
"border-radius: 0px;\n"
"font-family: Courier New;\n"
"color: #ffffff;\n"
"font-size: 14pt;\n"
"background: transparent;\n"
"padding: 10pt 20pt 10pt 20pt;\n"
"border: 5px solid #ffffff;\n"
"text-decoration: none;\n"
"}\n"
":hover {\n"
"background: white;\n"
"color: rgb(43, 46, 59);\n"
"border: 0px;\n"
"}")
        self.start_upload_b.setCheckable(False)
        self.start_upload_b.setChecked(False)
        self.start_upload_b.setDefault(False)
        self.start_upload_b.setFlat(False)
        self.start_upload_b.setObjectName("start_upload_b")
        self.horizontalLayout_5.addWidget(self.start_upload_b)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 11, 0, 1, 2)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.landing)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.subtitle_l.setText(_translate("mainWindow", "A prototype of cross lingual document clustering"))
        self.start_sentence_b.setText(_translate("mainWindow", "Input text"))
        self.start_upload_b.setText(_translate("mainWindow", "Upload files"))
